#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="zt-net"
prepare_service 20-zerotier
check_container_initialized

export NEXT_TELEMETRY_DISABLED=1
export NODE_ENV=production

if [ -z "${UI_CONTROLLER_URL}" ] ; then
    export ZT_ADDR=http://localhost:${CONTROLLER_LISTEN_PORT}
else
    export ZT_ADDR=${UI_CONTROLLER_URL}
fi

liftoff

print_start "Starting Zerotier UI ZT-Net ${ZTNET_VERSION}"
cd /app

silent exec s6-setuidgid "${ZEROTIER_USER}" \
                                node server.js


