on:
  push:
    paths:
      - '**'
      - '!CHANGELOG.md'
      - '!/examples/*'
      - '!LICENSE'
      - '!README.md'
      - '!/zabbix_templates/*'
jobs:
  prepare:
    uses: nfrastack/gha/.github/workflows/artifacts-encrypt.yml@main
    secrets: inherit
  build:
    needs: prepare
    strategy:
      matrix:
        include:
          - { distro: "alpine", distro_variant: "3.22", latest: "true", arch: "linux/amd64,linux/arm64" }
    uses: nfrastack/gha/.github/workflows/container-build_generic.yml@main
    with:
      base_image: "ghcr.io/nfrastack/container-nginx"
      distro: ${{ matrix.distro }}
      distro_variant: ${{ matrix.distro_variant }}
      image_variant: ${{ matrix.image_variant || '' }}
      tag: ${{ matrix.tag || '' }}
      latest: ${{ matrix.latest }}
      distro_latest: ${{ matrix.distro_latest }}
      platforms: ${{ matrix.arch }}
      push_dockerhub: ${{ matrix.push_dockerhub || true }}
      push_ghcr: ${{ matrix.push_ghcr || true }}
    secrets: inherit
  cleanup:
    needs: [ build ]
    uses: nfrastack/gha/.github/workflows/artifacts-remove.yml@main
    secrets: inherit

